### ISSUE TITLE
How to run C++ code for calculating the activity coefficients

### ISSUE THREAD

**Issue by GangqiangYu** [usnistgov/COSMOSAC#12]
The Open-source implementation of COSMO-SAC model is a greatly powerful and useful tool for the engineers and researchers. At present, I can use the .cosmo file to produce the .sigma file by the script “to_sigma.py”. I want to know how to run C++ code for calculating the activity coefficients because I don’t have a relatively rich Python experience. I carefully look at your publication (https://pubs.acs.org/doi/10.1021/acs.jctc.9b01016), but it is not found details for the calculation of activity coefficients. Could you provide a step-by-step tutorial similar to “VT-2005 database” (COSMO-SAC-VT-2005_Procedure.pdf) on calculating activity coefficients? If that is possible, I think this will greatly promote the wider and more convenient application of three models COSMO-SAC 2002, COSMO-SAC 2010, COSMO-SAC-dsp for the more scholoars who do not have a programming foundation in their future scientific research. I look forward to hearing from you！
[COSMO-SAC-VT-2005_Procedure.pdf](https://github.com/usnistgov/COSMOSAC/files/6300842/COSMO-SAC-VT-2005_Procedure.pdf)

**Comment by ianhbell** [comment]
There are some C++ examples in the tests: https://github.com/usnistgov/COSMOSAC/blob/master/tests/catch_tests.cpp

**Comment by GangqiangYu** [comment]
Thanks very much for your positive reply. I will carefully look at it.

**Comment by ianhbell** [comment]
The python interface is based upon the C++ one, so all the code you find in Python should map one-to-one to C++, just a few syntax changes are required.
