### ISSUE TITLE
Switching between the COSMO models

### ISSUE THREAD

**Issue by Bene94** [usnistgov/COSMOSAC#15]
Hello, 

I just started working with the tool and have a question regarding the different COSMO-Models. In the paper, three models are mentioned. I assumed I would switch between them with the function cosmo1 and cosmo3. Cosmo2 does not seem to be implemented. 

Does cosmo 1 correspond to  COSMO-SAC-2002  and cosmo3 toCOSMO-SAC-dsp? Or am I completely wrong?

Thanks for your time and the implementation of this tool!

**Comment by ianhbell** [comment]
Yes, that's about right.  There is no cosmo2 because the cosmo1 pertains to the single profile, and cosmo3 to the three-profile.
