### ISSUE TITLE
Upload/Add New Sigma Profiles into Existing UD Database

### ISSUE THREAD

**Issue by dmanheim89** [usnistgov/COSMOSAC#2]
Hello,

I was wondering if there is a way to integrate new sigma profiles (calculated using to_sigma.py) into the existing databases provided (i.e., University of Delaware). It seems that it is difficult (if not impossible) to perform COSMO-SAC calculations (using the built in C++ scripts) for a new profile that is not already included in the available databases. Any help would be much appreciated. Thanks!

**Comment by ianhbell** [comment]
Can you please provide a bit more context here?  Do you have a .cosmo file generated by a Dmol3 that you would like to add to the database? If so, that isn't a problem.  If you have another compound that you would like to add, but that you don't have a .cosmo file for, then you will need to find someone to do those calculations for you first.

**Comment by dmanheim89** [comment]
Please mark this issue as resolved. I am using Turbomole COSMO generated files instead of Dmol3 and have modified the to_sigma.py code to account for minor differences in the output of both software.  I was able to also modify the UD database text file to include the new sigma profiles and add them to the database so that I could perform the necessary COSMO-SAC calculations. On a side note, are you planning on implementing a multi-component version of the dispersion term (right now it only accepts two components)?

**Comment by ianhbell** [comment]
Even better would be if you wanted to contribute your changes to the ``to_sigma.py`` script so that others don't have to work through the same issues as you did :) 

My colleagues are better equipped to answer your questions about the dispersion term, but I think it should handle multiple components IIRC.  Can you please provide a non-working example in a new issue?
