### ISSUE TITLE
activity coefficients for several concentrations of mixture

### ISSUE THREAD

**Issue by mrk1414** [usnistgov/COSMOSAC#22]
I would like to determine the activity coefficients of some given pair of liquids for several
concentration values, e.g., 0.001, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 and 0.999.

Is there a way to do it within your package?

**Comment by ianhbell** [comment]
Have you seen the ``easy_COSMOSAC.py`` script? It simplifies the calling, and allows for arbitrary composition.  Also, the scripts here do too: https://github.com/usnistgov/COSMOSAC/blob/master/COSMO-SAC.ipynb
