### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by s08065451** [usnistgov/COSMOSAC#24]
When I do the last step of installation, there are warnings C4723, the Chinese in the image means that some values might be divided by zero. I wonder how to fix the problem. Thank you.
![image](https://user-images.githubusercontent.com/101328865/185745661-11c23664-68c3-4460-a4d0-ef668cbbfb70.png)

**Comment by ianhbell** [comment]
Those are all warnings. There should be an error down below?

**Comment by ianhbell** [comment]
Are you trying to use from Python? If so, then you just need: ``python setup.py install``

**Comment by s08065451** [comment]
Yes, I am going to use from python. And I have finished the step of python setup.py install. However, in python, I cannot import cCOSMO module, and I wonder how do I need to do to check if I successfully install.
![image](https://user-images.githubusercontent.com/101328865/185761919-40422b48-25a8-4dcf-9769-6193dbe37d55.png)

**Comment by ianhbell** [comment]
Leave out spyder for now. In the same shell where you did the build, try: ``python -c "import cCOSMO"``

If that works, then the problem is setup of your Spyder environment

**Comment by s08065451** [comment]
It doesn't show anything after I input python -c "import cCOSMO". Does it mean the input work?
![image](https://user-images.githubusercontent.com/101328865/185762324-5c3f8c1a-f0d5-4f45-a27d-744b681c9dca.png)

**Comment by ianhbell** [comment]
That's "good". It built properly. But it looks like you build in a MINGW environment. Why? That binary you built won't be compatible with cpython on windows. Better to use visual studio, there are free build tools, and guaranteed binary compatible builds.

**Comment by s08065451** [comment]
Oh, then I think I have been using the wrong build tools for a long time. And I am not familiar with Visual Studio, so I don't know how to build  with it. Which build tools should I use? I think I can learn on myself on Internet first, I am afraid that cannot catch up with your instruction and in turn waste your precious time.

**Comment by ianhbell** [comment]
See https://wiki.python.org/moin/WindowsCompilers. If it weren't for the cosmo files, I could automatically make a binary wheel.  But I want to make the licensing more clear, and it is unclear with the wheels. Also the wheels would be enormous.

**Comment by s08065451** [comment]
Thanks for your well-rounded reply! I will try these building tools and see
if they can work.

Ian Bell ***@***.***> 於 2022年8月21日 週日 03:19 寫道：
