### ISSUE TITLE
About tutorial

### ISSUE THREAD

**Issue by Fxzhou0919** [usnistgov/COSMOSAC#26]
Dear Prof. Bell
I want to ask if there is a tutorial for reference?

**Comment by ianhbell** [comment]
Please check through the python and jupyter notebooks. There are quite a few examples.

**Comment by Fxzhou0919** [comment]
Thank you!
I also want to ask one more question.
I used the Gaussian09 calculation to get my .cosmo file, and then call the to_sigma.py file. Unfortunately, i got the following error:
![1665923007213](https://user-images.githubusercontent.com/69492571/196035224-6ffbb061-bcdc-4f03-91a2-3529e8f9bbb1.png)
I also tested the .cosmo file in the /COSMOSAC/profiles/GAUSSIAN09_TEST directory and it works perfectly.
I want to ask what's wrong with my cosmo file?

**Comment by ianhbell** [comment]
Is your input path correct? Pointing to the desired file? I don't see any error message.

**Comment by rkrusushabh224** [comment]
I have the same issue. 
As I was trying to create a '.sigma' file for malonic acid, I got this message. Even though it is not an error, no '.sigma' file has been created. 
![Screenshot 2023-06-13 182349](https://github.com/usnistgov/COSMOSAC/assets/136467372/d90660b1-79c6-4b9c-8a7b-72c115105df3)
I have tried with both the averaging methods, I got the same output message. Refer to the image attached above.

**Comment by ianhbell** [comment]
Are you permitted to attach the file you tried to convert? Determining what input format you have has always been a bit fragile.

**Comment by mim134** [comment]
Hey, I've been having the same issue from Gaussian files. It seems to be caused by line 555 in to_sigma.py 
            assert(abs(sum(psigmaA)-meta['area [A^2]']) < 0.001)

The difference I'm getting for the molecule I'm testing is 0.0013. How important is this area check? I can generate a profile by removing this line but I'm concerned about the accuracy of the output.
Thank you

**Comment by ianhbell** [comment]
I'm guessing you are just running into rounding errors. Are you able to post the output file?

**Comment by mim134** [comment]
Here is the output file. Thanks!
[PFBA.txt](https://github.com/usnistgov/COSMOSAC/files/14639263/PFBA.txt)

**Comment by ianhbell** [comment]
The area check is just a sanity check that things are more or less ok. Can you please email me your Gaussian output to ian.bell@nist.gov and I will take a quick glance?

**Comment by mim134** [comment]
Sent! Thank you!
