### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by bjorn94** [usnistgov/COSMOSAC#27]
I am struggling with the installation process and would be very grateful if you could give me some guidance towards it. 
I have all the prerequisites. Then I try to install the code with the Cmake build using Visual Studio 2022, so I use the recommended commands for it with a slight change in the last line:
git clone --recursive --shallow-submodules https://github.com/usnistgov/COSMOSAC
cd COSMOSAC
mkdir build
cd build
cmake .. -G "Visual Studio 17 2022"
But when I run: cmake --build . --config Release
I receive the error message
![COSMOSAC_issue1](https://user-images.githubusercontent.com/126891727/222759007-f71c4e42-8e90-4d22-a4fc-d41ffa2ad437.JPG)
I do not quite understand what is the meaning of this error. 
Sorry for bothering with such a trivial issue, I am not familiar with this type of installations.

**Comment by ianhbell** [comment]
I think I fixed the problem. You'll need to pull and update your submodules with "git update submodule --recursive" and try again.

**Comment by bjorn94** [comment]
Thank you so much for a quick reply and the fixture! Finally, it works for me.

**Comment by ianhbell** [comment]
Good, happy to hear. Please close the issue.
