### ISSUE TITLE
compile error in Mac OS 10.13

### ISSUE THREAD

**Issue by y-kusaka** [usnistgov/COSMOSAC#4]
Hi, interesting project! I found a compile error in Mac OS 10.13 with
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044

---
I note that, after installing gcc via homebrew, setting
export CC=/usr/local/bin/gcc-10
export CXX=/usr/local/bin/g++-10
cmake worked finely.

**Comment by ianhbell** [comment]
Thanks for the report.  Indeed it is sometimes tricky on OSX to get the compilers to play nicely.  I can add your note to the README if you agree?  I don't think I've tested compilation on OSX yet, but I am glad to hear that it works successfully.

**Comment by y-kusaka** [comment]
of course.

**Comment by ianhbell** [comment]
Thanks, in 8186f3f7b5cebff2a9ab005fef9f4d64e06ea06d
